
# Manual testing http requests with extension REST Client

### POST /users/signup
POST http://{{host}}/api/users/signup
Content-Type: application/json

{
  "email": "tesata@gmail.com",
  "password": "123456789"
}


### POST /users/signin
POST http://{{host}}/api/users/signin
Content-Type: application/json

{
  "email": "tesata@gmail.com",
  "password": "123456789"
}


### GET /users/whoami
GET http://{{host}}/api/users/whoami
Authorization: Bearer {{token}}


