import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/providers/provider";
import { Toaster } from "@/components/ui/toaster";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { apiService } from "@/lib/services/api-service";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getAccessTokenRaw } = await getKindeServerSession();
  const accessTokenRaw = await getAccessTokenRaw();
  apiService.setAccessToken(accessTokenRaw);

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>{children}</Providers>
        <Toaster  />
      </body>
    </html>
  );
}
