
# Manual testing http requests

### POST /users/signup
POST http://chatwith-dev.io/api/users/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456"
}


### POST /users/signin
POST http://chatwith-dev.io/api/users/signin
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456"
}


### GET /users/:uid
GET http://chatwith-dev.io/api/users/5f3e3e3e3e3e3e3e3e3e3e3e

### GET /users/whoami
GET http://chatwith-dev.io/api/users/hello

### POST /users/logout
POST http://chatwith-dev.io/api/users/logout

