apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwith-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatwith-server
  template:
    metadata:
      labels:
        app: chatwith-server
    spec:
      containers:
        - name: chatwith-server
          image: matzapata/chatwith-server
          env:
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: chatwith-server-srv
spec:
  selector:
    app: chatwith-server
  ports:
    - name: chatwith-server
      protocol: TCP
      port: 3000
      targetPort: 3000
