apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwith-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: chatwith-server
          image: matzapata/chatwith-server
          env:
            # - name: HOST
            #   value: "HOST"
            # - name: MONGO_URI
            #   value: 'mongodb://auth-mongo-srv:27017/auth'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: chatwith-server-service
spec:
  selector:
    app: chatwith-server
  ports:
    - name: chatwith-server
      protocol: TCP
      port: 3000
      targetPort: 3000
