apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwith-server-pg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatwith-server-pg
  template:
    metadata:
      labels:
        app: chatwith-server-pg
    spec:
      containers:
        - name: chatwith-server-pg
          image: ankane/pgvector
          env: 
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: chatwith-server-pg-srv
spec:
  selector:
    app: chatwith-server-pg
  ports:
    - name: db
      port: 5432
      targetPort: 5432
