
# Manual testing http requests with extension REST Client

### GET /api/chats gets all the available chats for the user
GET http://{{host}}/api/chats
Authorization: Bearer {{token}}

### POST /api/chats creates a new chat from a file loading embeddings for it
POST http://{{host}}/api/chats
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

< ./data/example.txt
------boundary--

### GET /api/chats/:id Get the chat with the messages available
GET http://{{host}}/api/chats/95ce48c4-912e-4360-8d3d-a02134a4b050
Authorization: Bearer {{token}}

### DELETE /api/chats/:id delete the chat with the given id
DELETE http://{{host}}/api/chats/b0834fc8-3cee-4445-89b7-a547732d1934
Authorization: Bearer {{token}}


### PUT /api/chats/:id add a message to the chat
PUT http://{{host}}/api/chats/130b771c-3eab-42cd-9f62-954b48316a3d
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "message": "Who is juan?"
}



