
# Manual testing http requests with extension REST Client

### POST /api/payments/subscription creates a subscription link for the user
POST http://{{host}}/api/payments/subscription
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "variant_id": "99201"
}

### GET /api/payments/subscription gets the subscription for the logged in user
GET http://{{host}}/api/payments/subscription
Authorization: Bearer {{token}}

### GET /api/payments/subscription/portal
GET http://{{host}}/api/payments/subscription/portal
Authorization: Bearer {{token}}

### POST /api/payments/webhook - subscription_created
POST http://{{host}}/api/payments/webhook
Content-Type: application/json

{
  "data": {
    "id": "303492",
    "type": "subscriptions",
    "links": {
      "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492"
    },
    "attributes": {
      "urls": {
        "customer_portal": "https://matzapata.lemonsqueezy.com/billing?expires=1710354933&test_mode=1&user=528864&signature=a92dcd93e61d1b30bdb96b7c23f89491e3f82b1eb1d714ad6ac9e6edcef93ce2",
        "update_payment_method": "https://matzapata.lemonsqueezy.com/subscription/303492/payment-details?expires=1710419733&signature=b5f8779ab2a006b1ed23feca4104afa3ac5798782b6f44ca27ed583f36f4ab2e",
        "customer_portal_update_subscription": "https://matzapata.lemonsqueezy.com/billing/303492/update?expires=1710419733&user=528864&signature=748a2d53cc2f60fbcc825011f546a578347a74be494bf1ae81d0ca67af4bd753"
      },
      "pause": null,
      "status": "active",
      "ends_at": null,
      "order_id": 2284656,
      "store_id": 20568,
      "cancelled": false,
      "renews_at": "2024-04-13T12:35:27.000000Z",
      "test_mode": true,
      "user_name": "Matías Zapata",
      "card_brand": "visa",
      "created_at": "2024-03-13T12:35:28.000000Z",
      "product_id": 92548,
      "updated_at": "2024-03-13T12:35:33.000000Z",
      "user_email": "matuzapata@gmail.com",
      "variant_id": 99201,
      "customer_id": 2312870,
      "product_name": "Chatwith",
      "variant_name": "PRO",
      "order_item_id": 2245534,
      "trial_ends_at": null,
      "billing_anchor": 13,
      "card_last_four": "4242",
      "status_formatted": "Active",
      "first_subscription_item": {
        "id": 251686,
        "price_id": 388629,
        "quantity": 1,
        "created_at": "2024-03-13T12:35:33.000000Z",
        "updated_at": "2024-03-13T12:35:33.000000Z",
        "is_usage_based": false,
        "subscription_id": 303492
      }
    },
    "relationships": {
      "order": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/order",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/order"
        }
      },
      "store": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/store",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/store"
        }
      },
      "product": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/product",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/product"
        }
      },
      "variant": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/variant",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/variant"
        }
      },
      "customer": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/customer",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/customer"
        }
      },
      "order-item": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/order-item",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/order-item"
        }
      },
      "subscription-items": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/subscription-items",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/subscription-items"
        }
      },
      "subscription-invoices": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/subscription-invoices",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/subscription-invoices"
        }
      }
    }
  },
  "meta": {
    "test_mode": true,
    "event_name": "subscription_created",
    "webhook_id": "c6c9dfb1-f0c1-4f36-aa58-069bfccf48af",
    "custom_data": {
      "user_id": "kp_5105ff53dd434be2b62f7e75db19b5cf"
    }
  }
}

### POST /api/payments/webhook - subscription_payment_success -> Igonered for now. TODO:
POST http://{{host}}/api/payments/webhook
Content-Type: application/json

{
  "data": {
    "id": "749163",
    "type": "subscription-invoices",
    "links": {
      "self": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163"
    },
    "attributes": {
      "tax": 0,
      "urls": {
        "invoice_url": "https://app.lemonsqueezy.com/my-orders/59c6072d-84fb-4c2c-8b1f-2a78beec391b/subscription-invoice/749163?signature=cbae8ca4416aac191242dd57f2c3e5c5457969463a10856c8d3eabb5b603136b"
      },
      "total": 9000,
      "status": "paid",
      "tax_usd": 0,
      "currency": "USD",
      "refunded": false,
      "store_id": 20568,
      "subtotal": 9000,
      "test_mode": true,
      "total_usd": 9000,
      "user_name": "Matías Zapata",
      "card_brand": "visa",
      "created_at": "2024-03-13T12:55:10.000000Z",
      "updated_at": "2024-03-13T12:55:10.000000Z",
      "user_email": "matuzapata@gmail.com",
      "customer_id": 2312870,
      "refunded_at": null,
      "subtotal_usd": 9000,
      "currency_rate": "1.00000000",
      "tax_formatted": "$0.00",
      "tax_inclusive": false,
      "billing_reason": "updated",
      "card_last_four": "4242",
      "discount_total": 0,
      "subscription_id": 303492,
      "total_formatted": "$90.00",
      "status_formatted": "Paid",
      "discount_total_usd": 0,
      "subtotal_formatted": "$90.00",
      "discount_total_formatted": "$0.00"
    },
    "relationships": {
      "store": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163/relationships/store",
          "related": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163/store"
        }
      },
      "customer": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163/relationships/customer",
          "related": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163/customer"
        }
      },
      "subscription": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163/relationships/subscription",
          "related": "https://api.lemonsqueezy.com/v1/subscription-invoices/749163/subscription"
        }
      }
    }
  },
  "meta": {
    "test_mode": true,
    "event_name": "subscription_payment_success",
    "webhook_id": "512149c8-5694-4b9a-a9a8-066012ba11b0",
    "custom_data": {
      "user_id": "kp_5105ff53dd434be2b62f7e75db19b5cf"
    }
  }
}

### POST /api/payments/webhook - subscription_updated
POST http://{{host}}/api/payments/webhook
Content-Type: application/json

{
  "data": {
    "id": "303492",
    "type": "subscriptions",
    "links": {
      "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492"
    },
    "attributes": {
      "urls": {
        "customer_portal": "https://matzapata.lemonsqueezy.com/billing?expires=1710356115&test_mode=1&user=528864&signature=2f2e2f0b7d59e435a990bab316591997c3e80081f60a93f00ecdf21c2ad6513a",
        "update_payment_method": "https://matzapata.lemonsqueezy.com/subscription/303492/payment-details?expires=1710420915&signature=a5e63f3c9ad74ef93946769d3fb3a2c594ceae1f17a29b5e2465b889d5f17744",
        "customer_portal_update_subscription": "https://matzapata.lemonsqueezy.com/billing/303492/update?expires=1710420915&user=528864&signature=98f1981c580d1fca14c672776292fef3e0cf06ec8de5b871ac987008a84067ca"
      },
      "pause": null,
      "status": "cancelled",
      "ends_at": "2025-03-13T12:55:06.000000Z",
      "order_id": 2284656,
      "store_id": 20568,
      "cancelled": true,
      "renews_at": "2025-03-13T12:55:06.000000Z",
      "test_mode": true,
      "user_name": "Matías Zapata",
      "card_brand": "visa",
      "created_at": "2024-03-13T12:35:28.000000Z",
      "product_id": 92548,
      "updated_at": "2024-03-13T12:55:15.000000Z",
      "user_email": "matuzapata@gmail.com",
      "variant_id": 290380,
      "customer_id": 2312870,
      "product_name": "Chatwith",
      "variant_name": "PRO Year",
      "order_item_id": 2245534,
      "trial_ends_at": null,
      "billing_anchor": 13,
      "card_last_four": "4242",
      "status_formatted": "Cancelled",
      "first_subscription_item": {
        "id": 251686,
        "price_id": 388630,
        "quantity": 1,
        "created_at": "2024-03-13T12:35:33.000000Z",
        "updated_at": "2024-03-13T12:55:09.000000Z",
        "is_usage_based": false,
        "subscription_id": 303492
      }
    },
    "relationships": {
      "order": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/order",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/order"
        }
      },
      "store": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/store",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/store"
        }
      },
      "product": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/product",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/product"
        }
      },
      "variant": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/variant",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/variant"
        }
      },
      "customer": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/customer",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/customer"
        }
      },
      "order-item": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/order-item",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/order-item"
        }
      },
      "subscription-items": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/subscription-items",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/subscription-items"
        }
      },
      "subscription-invoices": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/subscription-invoices",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/subscription-invoices"
        }
      }
    }
  },
  "meta": {
    "test_mode": true,
    "event_name": "subscription_updated",
    "webhook_id": "cf17dcca-3469-4d9a-8636-0eafd336df6d",
    "custom_data": {
      "user_id": "kp_5105ff53dd434be2b62f7e75db19b5cf"
    }
  }
}


### POST /api/payments/webhook - subscription_cancelled -> No need for this one, already covered in the subscription_updated
POST http://{{host}}/api/payments/webhook
Content-Type: application/json

{
  "data": {
    "id": "303492",
    "type": "subscriptions",
    "links": {
      "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492"
    },
    "attributes": {
      "urls": {
        "customer_portal": "https://matzapata.lemonsqueezy.com/billing?expires=1710356115&test_mode=1&user=528864&signature=2f2e2f0b7d59e435a990bab316591997c3e80081f60a93f00ecdf21c2ad6513a",
        "update_payment_method": "https://matzapata.lemonsqueezy.com/subscription/303492/payment-details?expires=1710420915&signature=a5e63f3c9ad74ef93946769d3fb3a2c594ceae1f17a29b5e2465b889d5f17744",
        "customer_portal_update_subscription": "https://matzapata.lemonsqueezy.com/billing/303492/update?expires=1710420915&user=528864&signature=98f1981c580d1fca14c672776292fef3e0cf06ec8de5b871ac987008a84067ca"
      },
      "pause": null,
      "status": "cancelled",
      "ends_at": "2025-03-13T12:55:06.000000Z",
      "order_id": 2284656,
      "store_id": 20568,
      "cancelled": true,
      "renews_at": "2025-03-13T12:55:06.000000Z",
      "test_mode": true,
      "user_name": "Matías Zapata",
      "card_brand": "visa",
      "created_at": "2024-03-13T12:35:28.000000Z",
      "product_id": 92548,
      "updated_at": "2024-03-13T12:55:15.000000Z",
      "user_email": "matuzapata@gmail.com",
      "variant_id": 290380,
      "customer_id": 2312870,
      "product_name": "Chatwith",
      "variant_name": "PRO Year",
      "order_item_id": 2245534,
      "trial_ends_at": null,
      "billing_anchor": 13,
      "card_last_four": "4242",
      "status_formatted": "Cancelled",
      "first_subscription_item": {
        "id": 251686,
        "price_id": 388630,
        "quantity": 1,
        "created_at": "2024-03-13T12:35:33.000000Z",
        "updated_at": "2024-03-13T12:55:09.000000Z",
        "is_usage_based": false,
        "subscription_id": 303492
      }
    },
    "relationships": {
      "order": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/order",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/order"
        }
      },
      "store": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/store",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/store"
        }
      },
      "product": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/product",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/product"
        }
      },
      "variant": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/variant",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/variant"
        }
      },
      "customer": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/customer",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/customer"
        }
      },
      "order-item": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/order-item",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/order-item"
        }
      },
      "subscription-items": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/subscription-items",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/subscription-items"
        }
      },
      "subscription-invoices": {
        "links": {
          "self": "https://api.lemonsqueezy.com/v1/subscriptions/303492/relationships/subscription-invoices",
          "related": "https://api.lemonsqueezy.com/v1/subscriptions/303492/subscription-invoices"
        }
      }
    }
  },
  "meta": {
    "test_mode": true,
    "event_name": "subscription_cancelled",
    "webhook_id": "12b8d378-36f0-4e50-9d43-3e0a871f9cbd",
    "custom_data": {
      "user_id": "kp_5105ff53dd434be2b62f7e75db19b5cf"
    }
  }
}


# TODO: payment failed